export const routePaths = {
    signIn: "/auth/signin",
    signUp: "/api/v1/auth/signup",
    getUserData: "/api/v1/info/get-user-data",
    getWithdrawalHistory: "/api/v1/auth/get-withdrawal-history",
    updateBankingInfo: "/api/v1/update/update-banking-info",
    updatePassword: "/api/v1/update/update-password",
    createWithdrawOrder: "/api/v1/order/withdraw",
    getOrders: "/api/v1/order/get-orders",
    updateOrder: "/api/v1/order/update-order",
    foodDelivery: "/api/v1/info/get-food-delivery",
    allMenu: "/api/v1/info/get-all-menu",
    searchFood: "/api/v1/info/search-food-delivery",
    searchById: "/api/v1/info/search-by-id",
    purchaseOrder: "/api/v1/order/purchase",
    createOrder: "/api/v1/order/create-order",
    getOrder: "/api/v1/order/get-order",
}