enum StoreLocation {
    HaNoi = "Hà Nội",
    HoChiMinhCity = "Hồ Chí Minh",
    DaNang = "Đà Nẵng",
    HaiPhong = "Hải Phòng",
    CanTho = "Cần Thơ",
    Hue = "Huế",
    NhaTrang = "Nha Trang",
    Vinh = "Vinh",
    DaLat = "Đà Lạt",
    BienHoa = "Biên Hòa",
    QuiNhon = "Quy Nhơn",
    RachGia = "Rạch Giá",
    TamKy = "Tam Kỳ",
    VungTau = "Vũng Tàu",
    LongXuyen = "Long Xuyên",
    ThaiNguyen = "Thái Nguyên",
    BuonMaThuot = "Buôn Ma Thuột",
    Pleiku = "Pleiku",
    MyTho = "Mỹ Tho",
    CaMau = "Cà Mau",
    PhanThiet = "Phan Thiết",
    YenBai = "Yên Bái",
    SonLa = "Sơn La",
    DienBienPhu = "Điện Biên Phủ",
    LaoCai = "Lào Cai",
    TuyHoa = "Tuy Hòa",
    VinhYen = "Vĩnh Yên",
    ThaiBinh = "Thái Bình",
    SocTrang = "Sóc Trăng",
    BacLie = "Bạc Liêu",
    LongKhanh = "Long Khánh",
    ViThanh = "Vị Thanh",
}

export default StoreLocation;
