import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import {LiveChatWidgetProvider} from "@/contexts/liveChatWidgetContext";
import ReduxProviders from "@/app/ReduxProviders";
import NextauthSessionProviders from "@/components/NextauthSessionProviders";
import {ToastContainer, ToastContainerProps} from "react-toastify";
import { Toaster } from '@/ultis/component_default_props.ultis';
import {UserDataProvider} from "@/contexts/UserDataContext";
import NextUIProvider from "@/app/NextuiProvider";
import MenuBar from "@/components/Menu";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hanammilk - sữa ngon đến mọi nhà',
  description: 'Generated by create next app',
  // viewport: 'width=device-width, initial-scale=1',
  keywords: ["hanamilk", "sữa hanam"]
}

export default function RootLayout({
                                     children
                                   }: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body className={inter.className+ " h-full"}>
          <NextauthSessionProviders>
            <NextUIProvider>
              <ReduxProviders>
                <LiveChatWidgetProvider>
                  <UserDataProvider>
                   <div className={"w-full h-full"}>
                       <MenuBar />
                       {children}
                       <ToastContainer{...Toaster as ToastContainerProps}/>
                   </div>
                  </UserDataProvider>
                </LiveChatWidgetProvider>
              </ReduxProviders>
            </NextUIProvider>
          </NextauthSessionProviders>
        </body>
      </html>

  )
}
